config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/search',  to: 'search#search'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    passwords:          'users/passwords'
  }
  if Rails.env.development?  
    mount LetterOpenerWeb::Engine, at: "/letter_opener"  
  end 
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources   :users,          only: [:show, :index, :destroy]
  resources   :microposts,     only: [:index, :show, :create, :destroy] do
    resources :comments,       only: [:create, :destroy]
    end
  resources   :relationships,  only: [:create, :destroy]
  resources   :likes,          only: [:create, :destroy]
  resources   :notifications,  only: :index
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many   :comments,   dependent: :destroy
  has_many   :likes,      dependent: :destroy
  has_many   :like_users, through: :likes, source: :user
  has_many   :notifications, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

  validates  :user_id, presence: true
  validates  :content, presence: true, length: { maximum: 140 }, allow_blank: true
  validates  :picture, presence: true
  validate   :picture_size

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
    like_users.include?(user)
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ", current_user.id, user_id, id, 'like'])

    if temp.blank?
      notification = current_user.active_notifications.new(
        micropost_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(micropost_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      micropost_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def index
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments.page(params[:page]).per(20)
    @comment = @micropost.comments.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.user_id = current_user.id
    if @micropost.save
      flash[:success] = "投稿しました"
      redirect_to root_url
    else
      @feed_items = []
      render root_path
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" data-micropost-id="<%= micropost.id %>">
  <% unless controller_name == "users" %>
    <div class="micropost-header">
      <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
      <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    </div>
  <% end %>
  <span class="content home-content">
    <%= image_tag micropost.picture.url if micropost.picture? %>
    <%= micropost.content %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前
    <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, method: :delete,
                                       data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </span>
  <section class="like">
    <%= render "likes/likes", micropost: micropost %>
  </section>
  <%= link_to  "コメントする", micropost %>
</li>

app/views/microposts/show.html.erb
<div class="comment-wrapper border-top　mb-10 col-md-8">
  <h3 class="mt-5">コメント一覧</h3>
  <% @comments.each do |comment| %>
    <div class="comment">
      <% unless comment.user.blank? %>
        <%= link_to gravatar_for(comment.user, size: 30), user_path(comment.user) %>
      <% end %>
      <%= comment.user.name unless comment.user.blank? %>
      <br />
      <%= comment.content %>
      <% if comment.user == current_user %>
        <p><%= link_to 'コメントを削除する', micropost_comment_path(comment.micropost_id, comment.id), method: :delete %></p>
      <% end %>
    </div>
    <br />
  <% end %>
</div>

<%= paginate @comments %>

<div>
  <% if user_signed_in? %>
    <%= form_with(model: [@micropost, @comment], local: true) do |f| %>
      <%= f.text_area :content, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>