config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/search',  to: 'search#search'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    passwords:          'users/passwords'
  }
  if Rails.env.development?  
    mount LetterOpenerWeb::Engine, at: "/letter_opener"  
  end 
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources   :users,          only: [:show, :index, :destroy]
  resources   :microposts,     only: [:index, :show, :create, :destroy] do
    resources :comments,       only: [:create, :destroy]
    end
  resources   :relationships,  only: [:create, :destroy]
  resources   :likes,          only: [:create, :destroy]
  resources   :notifications,  only: :index
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Potestagram App</a>
    by <a href="https://www.instagram.com/">Potestagram</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to  "Post",    root_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Potestagram", root_path, id: "logo", class: "title"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= render "layouts/search" %></li>
        <li><%= link_to "",   root_path, class:"fas fa-home fa-2x" %></li>
        <% if user_signed_in? %>
          <li class="notification">
            <%= link_to "", notifications_path, class:"btn fas fa-heart fa-2x"  %>
              <% if unchecked_notifications.any? %>
                <i class= "fa fa-circle n-circle"></i>
              <% end %>
          </li>
          <li><%= link_to gravatar_for(current_user, size: 40), current_user, style:"padding: 6px;" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li>
                <%= link_to 'プロフィール変更', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>

app/views/layouts/_search.html.erb
<%= form_tag (users_path), method: 'get', class: "form-inline" do %>
  <%= text_field_tag :search, '', class: "form-control", placeholder: "検索" %>
  <%= submit_tag "検索" , name: nil, class: "btn form-control btn-default"%> 
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render "layouts/flash" %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>